name: 'Web Dev'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: "Prepare environment"
        run: |
          echo '${{ secrets.SEPL_KEYSTORE }}' | base64 -d > android/sepl.keystore
          echo '${{ secrets.KEY_PROPERTIES }}' | base64 -d > android/key.properties
          echo '${{ secrets.DOT_ENV_DEV }}' > .env
          v=$(grep -Po 'version: \K.*' pubspec.yaml)
          echo "VERSION=$v" >> .env
          echo "DISTRIBUTOR=github" >> .env
          echo "VERSION=$v" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/optimise-platform/mobile-app:dev
      - name: Deploy
        uses: wei/curl@v1
        with:
          args: -X POST -u ${{ secrets.RANCHER_TOKEN }} ${{ secrets.RANCHER_URL }}${{ secrets.RANCHER_SERVICE }}?action=redeploy
